print('===============Challenge 4===============')
x = input('Type something: ')

print('type primitie type of this value is', type(x))
print('is a number? ', x.isnumeric())
print('is printable? ', x.isprintable())
print('is a space? ',x.isspace())
print('is a title? ',x.istitle())
print('is lower case?', x.islower())
print('is upper case? ',x.isupper())
print('is an alpha numeric? ', x.isalnum())
