print('===============Challenge 4===============')
x = input('Type something: ')
print('is a number? ', x.isnumeric())
print('is decimal? ', x.isdecimal())
print('is a digit? ', x.isdigit())
print('is printable? ', x.isprintable())
print('is a space? ',x.isspace())
print('is a title? ',x.istitle())
print('is ASCII? ',x.isascii())
print('is a string? ', x.isalpha())
print('is lower case?', x.islower())
print('is upper case? ',x.isupper())
print('is a alpha numeric? ', x.isalnum())
