name = str(input('Type your name: ')).strip() 
splited = name.split()
print('your name in lower case is',name.lower())
print('your name in upper case is',name.upper())
print('your name have {} letters'.format(len(name.replace(' ',''))))
print('your first name is {} and it have {} letters'.format(splited[0],len(splited[0])))